import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "My-buss",
  description: "Generated by create next app",
  icons: "/Images/logo.png"
};

const style = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: "normal",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body
        style={style.style}
        className="light-mode flex flex-col transition-colors h-screen justify-between  overflow-x-hidden"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
