import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
//import Header from "./components/Header";

export const metadata: Metadata = {
  title: "My-buss",
  description: "Generated by create next app",
};

const style = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: "normal",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body style={style.style} className="light-mode flex flex-col h-screen transition-colors">
        <Header />
        {children}
      </body>
    </html>
  );
}
